# Ques 1 : What is the total revenue，total item sold and toatl trasaction generated by the café in 2023
SELECT
    SUM(`Total Spent`) AS Total_Revenue, SUM(`Quantity`) AS Total_Item_Sold, COUNT(`Transaction ID`) AS Total_Transaction
FROM cafe_sale.cafe;

# Ques 2: How much revenue is generated per month
SELECT
	Month, SUM(`Total Spent`) AS Monthly_Revenue
FROM cafe_sale.cafe
GROUP BY Month
order by Monthly_Revenue DESC ;

# Ques 3: Which items generate the highest total revenue?
SELECT
	Item, SUM(`Total Spent`) AS Total_Revenue
FROM cafe_sale.cafe
GROUP BY Item   
ORDER BY Total_Revenue DESC;

#Ques 4: Which items are sold the most by quantity?
SELECT
	Item, SUM(Quantity) AS Total_Quantity
FROM cafe_sale.cafe
GROUP BY Item   
ORDER BY Total_Quantity DESC;

# Ques 5: Which payment method is used most frequently?
SELECT
	`Payment Method`, Count(`Payment Method`) AS Count_Payment
FROM cafe_sale.cafe
GROUP BY `Payment Method`
ORDER BY Count_Payment DESC;

# Ques 6: How does revenue differ by payment method?
SELECT
	`Payment Method`, SUM(`Total Spent`) AS Total_Revenue
FROM cafe_sale.cafe
GROUP BY `Payment Method`
ORDER BY Total_Revenue DESC;

# Ques 7: Which location is the customer having the item?
SELECT
	`Location`, Count(`Location`) AS Count_Location
FROM cafe_sale.cafe
GROUP BY `Location`
ORDER BY Count_Location DESC;

# Ques 8: Do In-store or Takeaway orders generate more revenue?
SELECT
	Location, SUM(`Total Spent`) AS Total_Revenue
FROM cafe_sale.cafe
GROUP BY Location
ORDER BY Total_Revenue DESC;

# Ques 9: Which day of the week generates the highest revenue?
SELECT
	Weekday, SUM(`Total Spent`) AS Total_Revenue
FROM cafe_sale.cafe
GROUP BY Weekday
ORDER BY Total_Revenue DESC;

# Ques 10: Which month has the highest number of transactions?
SELECT
	Month, Count(`Transaction ID`) AS Count_Transaction
FROM cafe_sale.cafe
GROUP BY Month
ORDER BY Count_Transaction DESC
limit 1;


